name: Multiple evnt

on:
    push:
        branches:
            - main
            - dev
    pull_request:       
        branches:
            - main

jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Hello world
              run: echo "Hello world"            